### ISSUE TITLE
Apartment entrance does not update for property owner

### ISSUE THREAD

**Issue by ghost** [Qbox-project/qbx_properties#23]
### Summary

The apartment entrance coordinates only update from the config during the initial apartment selection before choosing an apartment. If the entrance is later moved in the config, it won't update for existing properties because the database coordinates are used instead of the config coordinates.

### Reproduction

1. Choose an apartment for your character
2. After the apartment is selected/stored in database, change the coords for that apartment in the config
3. Do a server restart then head to the new coords you placed in the config
4. The blip will be at the new coords but the property entrance menu will not

### Expected behavior

I expected the new coords entered in the config to be updated in the database so that when you do choose to change the coords the player's property entrance coords are updated as well

### Actual behavior

The new coords are never updated for the players that ALREADY own property at the changed location

### Current Version

v0.0.1

### Custom Resources

None

**Comment by ChatDisabled** [comment]
Not expected behaviour. This was discussed in discord.
