### ISSUE TITLE
Disconnecting while choosing an apartment keeps the player stuck in an interior on next login.

### ISSUE THREAD

**Issue by andreutu** [Qbox-project/qbx_properties#29]
### Summary

Disconnecting while choosing an apartment keeps the player stuck in the interior he's choosing the default apartment.

### Reproduction

1. Use the character creation menu from qbx_core. This is recommended, but if you have a custom one that implements the event `apartments:client:setupSpawnUI`, it _could_ work.
2. Disconnect while you're in the whiteboard menu when you're supposed to choose a default apartment.
3. Reconnect to the server, and spawn at the last location with this character.
4. You will be stuck in the apartment, with no way to get out other than by calling an admin to TP the player out.

### Expected behavior

qbx_properties should make the player choose the default apartment again if he didn't get a chance to do it because of a disconnect/quit/crash/etc..., or at least spawn the player at the default location

### Actual behavior

Upon spawning at the last location, you will be stuck in an apartment, with no means to get out by yourself. You will need additional support from someone to TP you out.

### Additional context

This is a side effect present with the default character selection. Not only you spawn at the wrong default last location, but you also don't have a player skin, so you will spawn with one of the random skins declared in qbx_core.

I will link a Discord support post that I did before I decided to write this issue, and a video which thoroughly shows this issue.

https://discord.com/channels/1012753553418354748/1280257523294933003
https://streamable.com/tqparl

### Current Version

v0.0.1, latest commit: 20e5762

### Custom Resources

Custom character resource, but the issue is present regrardless of the character selection resource. As long as it has the `apartments:client:setupSpawnUI` event, the issue appears.

**Comment by ChatDisabled** [comment]
Sorry for only seeing this issue now, but this should be resolved with this commit https://github.com/Qbox-project/qbx_properties/commit/04000f7ced5b5d6af4be36a051e18fc8d0865dc2
